adsb.api.url=https://api.adsb.lol/v2/mil
kafka.bootstrap.servers=localhost:9092
kafka.topic=military_flights
run.once=true
# schedule.cron=*/5 * * * *
# For SASL (optional):
# kafka.security.protocol=SASL_PLAINTEXT
# kafka.sasl.mechanism=PLAIN
# kafka.sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required username="user" password="pass";
