kafka.bootstrap.servers=localhost:9092
kafka.topic=military_flights
db.write.url=jdbc:postgresql://localhost:5432/military_watcher
db.write.username=military
db.write.password=military
ingestor.batch.size=100
